syntax = "proto3";

package paymentintegration;

import "Common/common.proto";

option csharp_namespace = "Payment.Grpc";

service PaymentIntegration {
  rpc CreatePaymentLink (CreatePaymentLinkRequest) returns (CreatePaymentLinkResponse);
  rpc GetPaymentStatus (GetPaymentStatusRequest) returns (GetPaymentStatusResponse);
}

message PaymentItem {
  string name = 1;
  int32 quantity = 2;
  int64 price = 3;
}

message CreatePaymentLinkRequest {
  string reference_type = 1;
  string reference_id = 2;
  int64 reference_code = 3;
  string provider = 4;
  int64 amount = 5;
  string currency = 6;
  string description = 7;
  repeated PaymentItem items = 8;
  string user_id = 9;
}

message PaymentLinkData {
  string payment_id = 1;
  string checkout_url = 2;
  string payment_link_id = 3;
  int64 amount = 4;
  string currency = 5;
  string status = 6;
}

message CreatePaymentLinkResponse {
  common.ResponseStatus status = 1;
  PaymentLinkData data = 2;
}

message GetPaymentStatusRequest {
  string reference_type = 1;
  string reference_id = 2;
  int64 reference_code = 3;
}

message PaymentStatusData {
  string payment_id = 1;
  string reference_type = 2;
  string reference_id = 3;
  int64 reference_code = 4;
  string provider = 5;
  string payment_link_id = 6;
  int64 amount = 7;
  string currency = 8;
  string status = 9;
  string paid_at = 10;
}

message GetPaymentStatusResponse {
  common.ResponseStatus status = 1;
  PaymentStatusData data = 2;
}
